#+TITLE: LaTeX Test
#+DATE: \today
#+AUTHOR: Fred Mitchell
#+EMAIL: fred.mitchell@gmx.de
#+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+OPTIONS: author:t c:nil creator:comment d:(not "LOGBOOK") date:t
#+OPTIONS: e:t email:nil f:t inline:t num:t p:nil pri:nil stat:t
#+OPTIONS: tags:t tasks:t tex:t timestamp:t toc:nil todo:t |:t
#+CREATOR: Emacs 25.3.1 (Org mode 8.2.10)
#+DESCRIPTION:
#+EXCLUDE_TAGS: noexport
#+KEYWORDS:
#+LANGUAGE: en
#+SELECT_TAGS: export
#+LATEX_CLASS: beamer
#+BEAMER_THEME: Frankfurt
#+BEAMER_INNER_THEME: rounded
* Spring Boot Exploraiton
  Basically, this is my playpen
  for exploring the power of Spring Boot.
** Java or Kotlin?
   I think Kotlin is the better choice,
   but I will play with both here.
** Notes
   Read all data from the given CSV files in a meaningful structure.

   Print out all books and magazines (could be a GUI, console, …)
   with all their details (with a meaningful output format).

   Find a book or magazine by its isbn.

   Find all books and magazines by their authors’ email.

   Print out all books and magazines with all their details sorted by title.
   This sort should be done for books and magazines together.

   Write Unit tests for one or more methods.

   Implement an interactive user interface for one or more of the main
   tasks mentioned above. This could be done by a website, on the console, etc.

   Add a book and a magazine to the data structure of your software 
   and export it to a new CSV files.
*** Kotlin alongside Java?
    Yes. Kotlin's extension is .kt
    Presumably, Mavin will know how to compile it.

